package org.sainm.codeatlas.analyzers.source;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Parses SMAP (Source Map) blocks generated by Jasper in compiled JSP servlet sources.
 * A SMAP maps generated Java .java lines back to the original .jsp file lines.
 *
 * <p>Jasper embeds SMAP as a block comment near the end of generated servlets:
 * <pre>
 * /* SMAP
 * UserPage_jsp.java
 * JSP
 * *S JSP
 * *F
 * + 0 user/page/UserPage.jsp
 * UserPage.jsp
 * + 1 user/page/UserPage.jsp
 * include/nav.jsp
 * *L
 * 1,1:123,5
 * 2,2:123,6
 * 123#1:2,5
 * 123#2:4,10
 * *E
 * *&#47;
 * </pre>
 */
public final class JasperSmapParser {
    private static final Pattern SMAP_BLOCK = Pattern.compile(
            "/\\*\\sSMAP(.*?)\\*\\/", Pattern.DOTALL);
    private static final Pattern STRATUM = Pattern.compile("\\*S\\s+(\\w+)");
    private static final Pattern FILE_SECTION = Pattern.compile("\\*F");
    private static final Pattern LINE_SECTION = Pattern.compile("\\*L");
    private static final Pattern END_SECTION = Pattern.compile("\\*E");
    private static final Pattern FILE_ENTRY = Pattern.compile(
            "\\+\\s+(\\d+)\\s+([A-Za-z0-9_.$#@/\\\\-]+)");
    private static final Pattern LINE_MAP = Pattern.compile(
            "(\\d+)(?:#(\\d+))?(?:,(\\d+))?:(\\d+)(?:,(\\d+))?");

    private JasperSmapParser() {
    }

    public static JasperSmapParser defaults() {
        return new JasperSmapParser();
    }

    public Optional<JasperSmapResult> parse(String generatedJavaContent, String absoluteJspPath) {
        if (generatedJavaContent == null || generatedJavaContent.isBlank()) {
            return Optional.empty();
        }
        if (absoluteJspPath == null || absoluteJspPath.isBlank()) {
            return Optional.empty();
        }
        Matcher smapMatcher = SMAP_BLOCK.matcher(generatedJavaContent);
        if (!smapMatcher.find()) {
            return Optional.empty();
        }
        String smapBody = smapMatcher.group(1);
        if (!STRATUM.matcher(smapBody).find()) {
            return Optional.empty();
        }
        Map<Integer, String> filePathsById = new LinkedHashMap<>();
        List<JspLineMapping> mappings = new ArrayList<>();
        boolean inFiles = false;
        boolean inLines = false;
        String pendingFileId = null;
        String pendingFilePath = null;
        for (String line : smapBody.split("\r?\n")) {
            line = line.trim();
            if (line.isEmpty()) continue;

            if (FILE_SECTION.matcher(line).find()) {
                inFiles = true;
                inLines = false;
                continue;
            }
            if (LINE_SECTION.matcher(line).find()) {
                if (pendingFileId != null) {
                    filePathsById.put(Integer.parseInt(pendingFileId), pendingFilePath);
                    pendingFileId = null;
                }
                inFiles = false;
                inLines = true;
                continue;
            }
            if (END_SECTION.matcher(line).find()) {
                break;
            }
            if (STRATUM.matcher(line).find()) {
                continue;
            }
            if (line.startsWith("*")) {
                continue;
            }
            if (inFiles) {
                Matcher fileMatcher = FILE_ENTRY.matcher(line);
                if (fileMatcher.find()) {
                    if (pendingFileId != null) {
                        filePathsById.put(Integer.parseInt(pendingFileId), pendingFilePath);
                    }
                    pendingFileId = fileMatcher.group(1);
                    pendingFilePath = fileMatcher.group(2);
                } else if (pendingFileId != null) {
                    filePathsById.put(Integer.parseInt(pendingFileId), line);
                    pendingFileId = null;
                }
            }
            if (inLines) {
                for (String token : line.split("\\s+")) {
                    if (token.isEmpty()) continue;
                    Matcher mapMatcher = LINE_MAP.matcher(token);
                    if (mapMatcher.matches()) {
                        int inputStart = Integer.parseInt(mapMatcher.group(1));
                        int inputFileId = mapMatcher.group(2) != null ? Integer.parseInt(mapMatcher.group(2)) : 0;
                        int inputLineCount = mapMatcher.group(3) != null ? Integer.parseInt(mapMatcher.group(3)) : 1;
                        int outputStart = Integer.parseInt(mapMatcher.group(4));
                        int outputIncrement = mapMatcher.group(5) != null ? Integer.parseInt(mapMatcher.group(5)) : 1;
                        int generatedLineEnd = outputStart + inputLineCount * outputIncrement - 1;
                        String jspFilePath = filePathsById.getOrDefault(inputFileId, "");
                        mappings.add(new JspLineMapping(
                                jspFilePath,
                                inputStart,
                                inputStart + inputLineCount - 1,
                                outputStart,
                                generatedLineEnd));
                    }
                }
            }
        }
        if (mappings.isEmpty()) {
            return Optional.empty();
        }
        return Optional.of(new JasperSmapResult(List.copyOf(filePathsById.values()), mappings));
    }

    public record JspLineMapping(
            String jspPath,
            int jspLineStart,
            int jspLineEnd,
            int generatedLineStart,
            int generatedLineEnd) {
    }

    public record JasperSmapResult(
            List<String> fileIds,
            List<JspLineMapping> mappings) {
        public JasperSmapResult {
            fileIds = List.copyOf(fileIds == null ? List.of() : fileIds);
            mappings = List.copyOf(mappings == null ? List.of() : mappings);
        }
    }
}
